name: Environments
description: Extracts all environments in the GitHub repository
inputs:
  token:
    description: GitHub token
    required: true
  repository:
    description: GitHub repository
    required: true
outputs:
  data:
    description: JSON array of environment names
    value: ${{ steps.get-environments.outputs.data }}
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install @octokit/action
      shell: bash
    - id: get-environments
      run: |
        DATA=$(node .github/actions/get-environments/script.mjs)
        echo "data=$DATA" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
