name: Deploy CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        environment: [ dev, sandbox ]
    uses: ./.github/workflows/echo.yml
    with:
        environment: ${{ matrix.environment }}
