name: Echo CI/CD

on:
  workflow_call:
    inputs: 
      environment: 
        required: true
        type: string

jobs:
  build:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        run: |
          echo ${{ github.ref_type }}
          echo ${{ github.ref_name }}
          echo ${{ github.sha }}
          echo ${{ secrets.DATA }}
          echo ${{ vars.DATA }}
